version: '3.8'

services:
  # Application Next.js Frontend uniquement
  p10-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: p10-clientapp-dev
    ports:
      - "3001:3001"  # Frontend sur port 3001
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3000  # Backend sur port 3000
      - NEXT_PUBLIC_APP_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - p10-network
    restart: unless-stopped
    user: "0:0"  # Run as root to avoid permission issues
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  p10-network:
    driver: bridge